name: Discord Alert

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para o Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚀 Novo commit/merge feito em `main` no repositório **calculadora-python** por `${{ github.actor }}`! Confira: ${{ github.event.head_commit.url }}"
